### ISSUE TITLE
Cross-platform support

### ISSUE THREAD

**Issue by 95-martin-orion** [quantumlib/qsim#8]
qsim and qsimh should be able to run on OSX, Linux, and Windows, at a minimum. We need to check the behavior on each platform and document any extra steps required.

If providing full support for a platform is not feasible prior to release, we should verify that Docker works as expected for that platform and provide instructions in the docs.

**Comment by gecrooks** [comment]
I was able to compile and install qsim on macOS (10.13), but it needed a few tweaks. I'd previously installed gcc with homebrew, but I had to remember to set CXX to homebrew's g++ compiler in /usr/local. And I had to add a couple of compiler flags.

`> make CXX=/usr/local/bin/g++-9 CXXFLAGS=" -O3 -mavx2 -mfma -fopenmp -Wl,-undefined,dynamic_lookup -Wno-maybe-uninitialized"`

The `-Wl,-undefined,dynamic_lookup` is suppressing `ld: symbol(s) not found for architecture x86_64` errors. 

The second flag is suppressing a warning that the compiler can't tell for sure that a particular variable is initialized.

```
../lib/run_qsimh.h:69:19: warning: 't0' may be used uninitialized in this function [-Wmaybe-uninitialized]
   69 |       IO::messagef("time elapsed %g seconds.\n", t1 - t0);
      |       ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by sergeisakov** [comment]
It works on macOS (10.14) using MacPorts' g++ compiler without any additional flags (no warnings generated):

make CXX=g++-mp-9 CXXFLAGS="-O3 -mavx2 -mfma -fopenmp"

**Comment by 95-martin-orion** [comment]
I'll look into adding continuous tests for this using the same infrastructure as TFQ relies on.

**Comment by 95-martin-orion** [comment]
Kokoro builds for Windows, MacOS, and Linux are now required for all PRs. If the Kokoro build does not run, try adding the `kokoro:run` label to the PR.
